#!/bin/bash

set -e

# Variables
DB_NAME=MYSQL_DATABASE
DB_USER=MYSQL_USER
DB_PASSWORD=MYSQL_ROOT_PASSWORD
DEV_DB_PASSWORD=MYSQL_PASSWORD

# Create the database
mysql -u root <<-EOSQL
  CREATE DATABASE IF NOT EXISTS $DB_NAME;
  CREATE USER 'developer'@'%' IDENTIFIED BY '$DEV_DB_PASSWORD';
  GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
  FLUSH PRIVILEGES;
EOSQL
