---
apiVersion: v1
kind: Pod
metadata:
  labels:
    br.com.bb.sigla: psc
    br.com.bb.compilacao: false
    br.com.bb.compilacao.linguagem: docker
    br.com.bb.compilacao.versao: 18
spec:
  imagePullSecrets:
  - name: atfregistry
  tolerations:
    - key: "papel.node.k8s.bb/workload"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    papel.node.k8s.bb/workload: true
  slaveConnectTimeout: 180000
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker-socket-volume
  - hostPath:
      path: /var/tmp/jenkins_slave/
      type: ""
    name: temp-home-volume
  containers:
  - name: jnlp
    image: atf.intranet.bb.com.br:5001/bb/aic/aic-jenkins-slave:3.30.0
    tty: true
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"
  - name: deploy
    image: atf.intranet.bb.com.br:5001/bb/psc/psc-helm:2.14.0
    tty: true
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"
  - name: build
    image: atf.intranet.bb.com.br:5001/bb/big/big-source-to-image:0.1.0
    tty: true
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket-volume
    command:
    - cat
